### ISSUE TITLE
macOS build: conflicting types for 'clock_gettime'

### ISSUE THREAD

**Issue by ax3l** [GTkorvo/evpath#47]
I am trying to build ADIOS 2.6.0 on macOS 10.15, compatible with SDK 10.9.
CMake:
```
cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DADIOS2_BUILD_EXAMPLES=OFF -DADIOS2_BUILD_TESTING=OFF -DADIOS2_USE_BZip2=OFF -DADIOS2_USE_Fortran=OFF -DADIOS2_USE_MPI=OFF -DADIOS2_USE_PNG=OFF -DHDF5_USE_STATIC_LIBRARIES:BOOL=ON -DCMAKE_DISABLE_FIND_PACKAGE_LibFFI=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_BISON=TRUE -DCMAKE_INSTALL_PREFIX=/usr/local ../ADIOS2-2.6.0
-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032
```

I get the following compile error with EVPATH.
```
[ 42%] Building C object thirdparty/EVPath/EVPath/CMakeFiles/EVPath.dir/cmzplenet.c.o
In file included from /Users/runner/work/openPMD-api/openPMD-api/src/build-ADIOS2/thirdparty/EVPath/EVPath/cmzplenet.c:21:
/Users/runner/work/openPMD-api/openPMD-api/src/ADIOS2-2.6.0/thirdparty/EVPath/EVPath/zpl-enet/include/enet.h:4905:13: error: conflicting types for 'clock_gettime'
        int clock_gettime(int X, struct timespec *ts) {
            ^
/Applications/Xcode_11.6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/time.h:178:5: note: previous declaration is here
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);
    ^
1 error generated.
```

Full log: [adios2_evpath.zip](https://github.com/GTkorvo/evpath/files/5186636/adios2_evpath.zip)

Cross-link: https://github.com/openPMD/openPMD-api/commit/9a8344af81ef1bc70c8e3c10a511020d78bba85b

**Comment by eisenhauer** [comment]
Hmm.  Something wonky going on here that isn't immediately obvious.  ZPL ENET is an something that got pulled into evpath to try to address prior problems with the base ENET release, but which is not currently used.  We could blow it away, or disable it with EVPATH_USE_ZPL_ENET=Off, but I'm curious what this problem is.  The line is protected with 
`   #elif __APPLE__ && __MAC_OS_X_VERSION_MIN_REQUIRED < 101200
`
Clearly designed to keep this from being active when there's a decl for clock_gettime.  I'd assume it's structured as it is because ZPL ENET is an include-only package, so they wouldn't want to check for an actual define, but are doing it indirection with the version info.   What I don't know yet is why this mechanism isn't working for your compiler/OS pair.  I've been doing OSX development for ADIOS2 for years, currently on 10.5.6 and haven't run into this...

OK it looks like I'm at Clang 12.0.0.12000026, a newer version than yours.  Do you maybe have an XCode update waiting to be installed?

**Comment by ax3l** [comment]
This might be caused by the need that I am building releases for openPMD-api for PyPI which are compatible with macOS SDK 10.9 (`MACOSX_DEPLOYMENT_TARGET=10.9`).
- apple: https://opensource.apple.com/source/cctools/cctools-862/libstuff/macosx_deployment_target.c.auto.html
- SO: https://stackoverflow.com/questions/25352389/what-is-the-difference-between-macosx-deployment-target-and-mmacosx-version-min
- CMake: https://cmake.org/cmake/help/latest/envvar/MACOSX_DEPLOYMENT_TARGET.html
- CD: https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/#macos-and-deployment-target-versions / https://github.com/joerick/cibuildwheel/pull/322#issuecomment-615478878

**Comment by eisenhauer** [comment]
I might tend to agree that there's something wrong with the check.  Another factor that seems to be coming into play is that MAC_OS_X_VERSION_MIN_REQUIRED may have changed from a 6-character string to a 4-digit number (or vice versa, not sure).  But the uglier problem is that this issuee is in the ZPL ENET code, so any bug report really needs to go upstream.  However, OSX Mavericks is well past its EoL date, so you might have a problem getting them to care.  Can I suggest adding -DEVPATH_USE_ZPL=Off to your CMake line to avoid the problem?

**Comment by eisenhauer** [comment]
So, is EVPATH_USE_ZPL=Off a viable workaround for you on this?

**Comment by ax3l** [comment]
Hm, what does `EVPATH_USE_ZPL=OFF` imply? :)

**Comment by eisenhauer** [comment]
It simply turns off the building the bit of code that that seems to be causing trouble.  The functionality that that code provides is not currently utilized by ADIOS2 (or by default in EVPath), so everything should function as you would expect.

**Comment by ax3l** [comment]
Thank you. I'll give it a try and report back what CI says :)

**Comment by ax3l** [comment]
@eisenhauer when I am building ADIOS2 I get this:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    EVPATH_USE_ZPL
```

**Comment by ax3l** [comment]
Did you mean `-DEVPATH_USE_ZPL_ENET=OFF`?

**Comment by eisenhauer** [comment]
Ah yes, sorry...

**Comment by ax3l** [comment]
Works as a work-around, thanks a lot! :)

**Comment by ax3l** [comment]
Confirming that macOS 11.0+ works with `-DEVPATH_USE_ZPL_ENET=ON` (the default).
